const FETCH_FAVOURITE_POKEMON = "FETCH_FAVOURITE_POKEMON"
const CREATE_FAVOURITE_POKEMON = "CREATE_FAVOURITE_POKEMON"
const REMOVE_FAVOURITE_POKEMON = "REMOVE_FAVOURITE_POKEMON"

export { FETCH_FAVOURITE_POKEMON, CREATE_FAVOURITE_POKEMON, REMOVE_FAVOURITE_POKEMON }